/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.shannon.michaelAstrology

import de.thmac.Swetest
import de.thmac.swisseph.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(/*args: Array<String>*/) {
    var swed = SwissData()
    var sl = SwissLib()
    var sw = SwissEph()
    var sd: SweDate? = null
    var sh = SweHel(sw, sl, null, swed)


    //sd = SweDate(tjd, gregflag)

    val universal_time = true

}
