/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.shannon.michaelAstrology

import org.assertj.core.api.Assertions.assertThat
import java.time.OffsetDateTime
import java.time.ZoneOffset
import kotlin.test.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertThat(classUnderTest.greeting).isNotNull()
    }

    @Test
    fun localDateTime() {
        val dateTime = OffsetDateTime.parse("2019-08-15T14:30:00+00:00")
        assertThat(dateTime.hour).isEqualTo(14)
        assertThat(dateTime.withOffsetSameInstant(ZoneOffset.UTC).hour).isEqualTo(14)
        println(dateTime.toString())
    }

    @Test
    fun localDateTime2() {
        val dateTime = OffsetDateTime.parse("2019-08-15T14:30:00+01:00")
        assertThat(dateTime.hour).isEqualTo(14)
        assertThat(dateTime.withOffsetSameInstant(ZoneOffset.UTC).hour).isEqualTo(13)
        println(dateTime.toString())
    }
}
