/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.shannon.MichaelAstrology

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertThat(classUnderTest.greeting).isNotNull()
    }
}
